fix(label): Include label name on update
william20111/terraform-provider-thousandeyes pull request #54
Opened 2021-05-05 15:26 UTC by omwbennett

Currently label updates don't work if you want to do something like add an additional agent to a label resource

2021-05-12 13:18 UTC, johntdyer approved these changes

2021-05-12 13:18 UTC, johntdyer commented
Thanks !

2021-05-12 13:18 UTC, johntdyer commented
Is there any test you can add for this ?

2021-05-12 13:19 UTC, johntdyer requested changes
requesting test coverage

2021-05-16 14:58 UTC, omwbennett commented
@johntdyer Sure, it seems like acceptance tests as outlined [here](https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html) would make the most sense for this change, although that would likely lead to a much larger PR as there doesn't seem to be any existing tests for this Terraform provider. Are you ok with accepting this PR as is? I'm happy to open another one with acceptance tests when I get around to it.

2021-07-06 17:52 UTC, johntdyer commented
@omwbennett  - I would have to defer to @william20111 on that

2021-07-06 18:11 UTC, william20111 commented
Without a thousandeyes sandbox to run CI/CD integration tests against PRs I dont see us having those. So im comfortable merging this if you are @johntdyer

2021-09-03 14:08 UTC, johntdyer approved these changes

2021-09-03 14:08 UTC, merged